language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1
  - 2.0.0
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
